#!/bin/bash
# StatusLine Setup - PS1 to Statusline Converter
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PRESET="git-aware"
FORMAT="tmux"

usage() {
    cat << USAGE
StatusLine Setup - Configure statusLine from PS1

Usage: $(basename "$0") [OPTIONS]
OPTIONS:
    --parse-ps1 PS1     Parse an existing PS1 string
    --preset PRESET     Use a preset (minimal|git-aware|powerline|full)
    --format FORMAT     Output format (tmux|bash|zsh|starship)
    --show-presets      Show available presets
    --help             Show this help
USAGE
    exit 0
}

declare -A PRESETS
PRESETS["minimal"]="left:#{host_short} #{b:pane_title} right:%H:%M %d"
PRESETS["git-aware"]="left:git (#{git_current_branch} #{git_status}) right:%H:%M %d"
PRESETS["powerline"]="left:#{b:pane_title} | git:#{git_current_branch} | path:#{b:pane_current_path} right:%H:%M | %d"
PRESETS["full"]="left:host:#{host_short} | session:#S | pane:#{b:pane_title} right:git:#{git_current_branch} | time:%H:%M"

parse_ps1() {
    local ps1="$1"
    echo "Parsing PS1: $ps1"
}

generate_tmux() {
    cat << TMUX
# Generated by statusline-setup
# Preset: $PRESET

set -g status on
set -g status-interval 5
set -g status-justify left
set -g status-position bottom
set -g status-length 120
set -g status-style "bg=#1e1e1e,fg=#cccccc"
set -g window-status-style "bg=#2d2d2d,fg=#888888"
set -g window-status-current-style "bg=#444444,fg=#ffffff,bold"
set -g status-left "${PRESETS[$PRESET]}"
TMUX
}

generate_bash() {
    cat << BASH
# Generated by statusline-setup
git_branch() { git branch 2>/dev/null | grep '^\*' | cut -d' ' -f2; }
PS1='\[\033[1;32m\]\u@\h\[\033[0m\]:\[\033[1;34m\]\w\[\033[0m\]$(git_branch 2>/dev/null && echo " ($(git_branch))")$ '
BASH
}

generate_zsh() {
    cat << ZSH
# Generated by statusline-setup
autoload -Uz vcs_info
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
zstyle ':vcs_info:git:*' formats '%b'
PS1='%F{green}%n@%m%f:%F{blue}%~%f%\$vcs_info_msg_0s%# '
ZSH
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --parse-ps1) PARSE_PS1=true; INPUT_PS1="$2"; shift 2 ;;
        --preset) PRESET="$2"; shift 2 ;;
        --format) FORMAT="$2"; shift 2 ;;
        --show-presets) echo "Presets: ${!PRESETS[@]}"; exit 0 ;;
        --help) usage ;;
        *) shift ;;
    esac
done

case "$FORMAT" in
    tmux) generate_tmux ;;
    bash) generate_bash ;;
    zsh) generate_zsh ;;
    *) echo "Unknown format: $FORMAT" ;;
esac
